## Titanic

In [3]:
import polars as pl

df = pl.read_csv("titanic.csv")

# Basic descriptive statistics
print("=== Descriptive Statistics ===")
print(df.describe())

# Value counts for categorical columns
print("\n=== Categorical Column Value Counts ===")
for col in df.columns:
    if df[col].dtype == pl.Utf8:
        print(f"\n{col} value counts:")
        print(df[col].value_counts().sort("count", descending=True).head())

=== Descriptive Statistics ===
shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

=== Categorical Column Value Counts ===

Name value counts:
shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ Name                            ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Andersson, Mrs. Anders Johan (… ┆ 1     │
│ Allen, Miss. Elisabeth Walton   ┆ 1     │
│ Lurette, Miss. Elise            ┆ 1     │
│ Smart, Mr. John Montgomery      ┆ 1     │
│ Cherry, Miss. Gladys            ┆ 1     │
└─────────────────────────────────┴───────┘

Sex value counts:
shape: (2, 2)
┌────────┬───────┐
│ Sex    ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ male   ┆ 577   │
│ female ┆ 314   │
└────────┴───────┘

Ticket value counts:
shape: (5, 2)
┌──────────┬───────┐
│ Ticket   ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ 347082   ┆ 7     │
│ 1601     ┆ 7     │
│ CA. 2343 ┆ 7     │
│ 3101295  ┆ 6     │
│ CA 2144  ┆ 6     │
└──────────┴───────┘

Cabin value counts:
shape: (5, 2)
┌─────────────┬───────┐
│ Cabin       ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ null        ┆ 687   │
│ B96 B98     ┆ 4     │
│ G6          ┆ 4     │
│ C23 C25 C27 ┆ 4     │
│ F2          ┆ 3     │
└─────────────┴───────┘

Embarked value counts:
shape: (4, 2)
┌──────────┬───────┐
│ Embarked ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ S        ┆ 644   │
│ C        ┆ 168   │
│ Q        ┆ 77    │
│ null     ┆ 2     │
└──────────┴───────┘

## Iris

In [2]:
import polars as pl

df = pl.read_csv("iris.csv") 

# Descriptive statistics
print("=== Descriptive Statistics ===")
print(df.describe())

# Value counts
print("\n=== Categorical Column Value Counts ===")
for col in df.columns:
    if df[col].dtype == pl.Utf8:
        print(f"\n{col} value counts:")
        print(df[col].value_counts().sort("count", descending=True).head())

=== Descriptive Statistics ===
shape: (9, 7)
┌────────────┬───────────┬──────────────┬──────────────┬──────────────┬──────────────┬─────────────┐
│ statistic  ┆ Id        ┆ SepalLengthC ┆ SepalWidthCm ┆ PetalLengthC ┆ PetalWidthCm ┆ Species     │
│ ---        ┆ ---       ┆ m            ┆ ---          ┆ m            ┆ ---          ┆ ---         │
│ str        ┆ f64       ┆ ---          ┆ f64          ┆ ---          ┆ f64          ┆ str         │
│            ┆           ┆ f64          ┆              ┆ f64          ┆              ┆             │
╞════════════╪═══════════╪══════════════╪══════════════╪══════════════╪══════════════╪═════════════╡
│ count      ┆ 150.0     ┆ 150.0        ┆ 150.0        ┆ 150.0        ┆ 150.0        ┆ 150         │
│ null_count ┆ 0.0       ┆ 0.0          ┆ 0.0          ┆ 0.0          ┆ 0.0          ┆ 0           │
│ mean       ┆ 75.5      ┆ 5.843333     ┆ 3.054        ┆ 3.758667     ┆ 1.198667     ┆ null        │
│ std        ┆ 43.445368 ┆ 0.828066     ┆ 0.433594     ┆ 1.76442      ┆ 0.763161     ┆ null        │
│ min        ┆ 1.0       ┆ 4.3          ┆ 2.0          ┆ 1.0          ┆ 0.1          ┆ Iris-setosa │
│ 25%        ┆ 38.0      ┆ 5.1          ┆ 2.8          ┆ 1.6          ┆ 0.3          ┆ null        │
│ 50%        ┆ 76.0      ┆ 5.8          ┆ 3.0          ┆ 4.4          ┆ 1.3          ┆ null        │
│ 75%        ┆ 113.0     ┆ 6.4          ┆ 3.3          ┆ 5.1          ┆ 1.8          ┆ null        │
│ max        ┆ 150.0     ┆ 7.9          ┆ 4.4          ┆ 6.9          ┆ 2.5          ┆ Iris-virgin │
│            ┆           ┆              ┆              ┆              ┆              ┆ ica         │
└────────────┴───────────┴──────────────┴──────────────┴──────────────┴──────────────┴─────────────┘

=== Categorical Column Value Counts ===

Species value counts:
shape: (3, 2)
┌─────────────────┬───────┐
│ Species         ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ Iris-versicolor ┆ 50    │
│ Iris-virginica  ┆ 50    │
│ Iris-setosa     ┆ 50    │
└─────────────────┴───────┘

## Netflix

In [4]:
import polars as pl

df = pl.read_csv("netflix_titles.csv")

# Descriptive statistics
print("=== Descriptive Statistics ===")
print(df.describe())

# Value counts
print("\n=== Categorical Column Value Counts ===")
for col in df.columns:
    if df[col].dtype == pl.Utf8:
        print(f"\n{col} value counts:")
        print(df[col].value_counts().sort("count", descending=True).head())

=== Descriptive Statistics ===
shape: (9, 13)
┌────────────┬─────────┬─────────┬─────────────┬───┬────────┬──────────┬─────────────┬─────────────┐
│ statistic  ┆ show_id ┆ type    ┆ title       ┆ … ┆ rating ┆ duration ┆ listed_in   ┆ description │
│ ---        ┆ ---     ┆ ---     ┆ ---         ┆   ┆ ---    ┆ ---      ┆ ---         ┆ ---         │
│ str        ┆ str     ┆ str     ┆ str         ┆   ┆ str    ┆ str      ┆ str         ┆ str         │
╞════════════╪═════════╪═════════╪═════════════╪═══╪════════╪══════════╪═════════════╪═════════════╡
│ count      ┆ 8807    ┆ 8807    ┆ 8807        ┆ … ┆ 8803   ┆ 8804     ┆ 8807        ┆ 8807        │
│ null_count ┆ 0       ┆ 0       ┆ 0           ┆ … ┆ 4      ┆ 3        ┆ 0           ┆ 0           │
│ mean       ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ std        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ min        ┆ s1      ┆ Movie   ┆ #Alive      ┆ … ┆ 66 min ┆ 1 Season ┆ Action &    ┆ "Bridgerton │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆ Adventure   ┆ " cast      │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆             ┆ members     │
│            ┆         ┆         ┆             ┆   ┆        ┆          ┆             ┆ shar…       │
│ 25%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ 50%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ 75%        ┆ null    ┆ null    ┆ null        ┆ … ┆ null   ┆ null     ┆ null        ┆ null        │
│ max        ┆ s999    ┆ TV Show ┆ 최강전사    ┆ … ┆ UR     ┆ 99 min   ┆ Thrillers   ┆ “Last       │
│            ┆         ┆         ┆ 미니특공대  ┆   ┆        ┆          ┆             ┆ Chance U”   │
│            ┆         ┆         ┆ : 영웅의    ┆   ┆        ┆          ┆             ┆ hits the    │
│            ┆         ┆         ┆ 탄생        ┆   ┆        ┆          ┆             ┆ hardw…      │
└────────────┴─────────┴─────────┴─────────────┴───┴────────┴──────────┴─────────────┴─────────────┘

=== Categorical Column Value Counts ===

show_id value counts:
shape: (5, 2)
┌─────────┬───────┐
│ show_id ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ s8411   ┆ 1     │
│ s4352   ┆ 1     │
│ s6075   ┆ 1     │
│ s255    ┆ 1     │
│ s45     ┆ 1     │
└─────────┴───────┘

type value counts:
shape: (2, 2)
┌─────────┬───────┐
│ type    ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ Movie   ┆ 6131  │
│ TV Show ┆ 2676  │
└─────────┴───────┘

title value counts:
shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ title                           ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Indian Horse                    ┆ 1     │
│ The Love Affair                 ┆ 1     │
│ Bruno and Boots: This Can't Be… ┆ 1     │
│ The Last of the Schmucks        ┆ 1     │
│ The Call                        ┆ 1     │
└─────────────────────────────────┴───────┘

director value counts:
shape: (5, 2)
┌────────────────────────┬───────┐
│ director               ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ null                   ┆ 2634  │
│ Rajiv Chilaka          ┆ 19    │
│ Raúl Campos, Jan Suter ┆ 18    │
│ Suhas Kadav            ┆ 16    │
│ Marcus Raboy           ┆ 16    │
└────────────────────────┴───────┘

cast value counts:
shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ cast                            ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ null                            ┆ 825   │
│ David Attenborough              ┆ 19    │
│ Vatsal Dubey, Julie Tejwani, R… ┆ 14    │
│ Samuel West                     ┆ 10    │
│ Jeff Dunham                     ┆ 7     │
└─────────────────────────────────┴───────┘

country value counts:
shape: (5, 2)
┌────────────────┬───────┐
│ country        ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ United States  ┆ 2818  │
│ India          ┆ 972   │
│ null           ┆ 831   │
│ United Kingdom ┆ 419   │
│ Japan          ┆ 245   │
└────────────────┴───────┘

date_added value counts:
shape: (5, 2)
┌───────────────────┬───────┐
│ date_added        ┆ count │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ January 1, 2020   ┆ 109   │
│ November 1, 2019  ┆ 89    │
│ March 1, 2018     ┆ 75    │
│ December 31, 2019 ┆ 74    │
│ October 1, 2018   ┆ 71    │
└───────────────────┴───────┘

rating value counts:
shape: (5, 2)
┌────────┬───────┐
│ rating ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ TV-MA  ┆ 3207  │
│ TV-14  ┆ 2160  │
│ TV-PG  ┆ 863   │
│ R      ┆ 799   │
│ PG-13  ┆ 490   │
└────────┴───────┘

duration value counts:
shape: (5, 2)
┌───────────┬───────┐
│ duration  ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ 1 Season  ┆ 1793  │
│ 2 Seasons ┆ 425   │
│ 3 Seasons ┆ 199   │
│ 90 min    ┆ 152   │
│ 93 min    ┆ 146   │
└───────────┴───────┘

listed_in value counts:
shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ listed_in                       ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Dramas, International Movies    ┆ 362   │
│ Documentaries                   ┆ 359   │
│ Stand-Up Comedy                 ┆ 334   │
│ Comedies, Dramas, Internationa… ┆ 274   │
│ Dramas, Independent Movies, In… ┆ 252   │
└─────────────────────────────────┴───────┘

description value counts:
shape: (5, 2)
┌─────────────────────────────────┬───────┐
│ description                     ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Paranormal activity at a lush,… ┆ 4     │
│ Challenged to compose 100 song… ┆ 3     │
│ A surly septuagenarian gets an… ┆ 3     │
│ Multiple women report their hu… ┆ 3     │
│ Two quirky cats, Ollie and Moo… ┆ 2     │
└─────────────────────────────────┴───────┘